version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancedb
    volumes:
      - balancedb-dev-data:/var/lib/postgresql/data
      - ././src/main/resources/db/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5435:5432"
volumes:
  balancedb-dev-data: