version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancedb
    volumes:
      - ./src/main/resources/db/scripts/01-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
volumes:
  balancedb-data: