version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancedb
    volumes:
      - balancedb-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
volumes:
  balancedb-data: