spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/balancedb
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  liquibase:
    enabled: false
    change-log: db/changelogs.yaml
server:
  port: 8081