spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/balancedb
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath:/db/data/data.sql
  liquibase:
    drop-first: true
    default-schema: balance
server:
  port: 8082