spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://balance_db:5432/balancedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: db/changelogs.yaml
server:
  port: 8081